AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # S3 Bucket Create
  S3BucketForLambda:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-mtc-lambda
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  # S3 Bucket Policy Create
  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3BucketForLambda
      PolicyDocument:
        Statement:
          - Sid: APIReadForGetBucketObjects
            Effect: Allow
            Action: 's3:GetObject'
            Principal:
              AWS: '*'
            Resource: !Sub arn:aws:s3:::${S3BucketForLambda}/*
  # CI/CD IAM Role for CodeBuild Create
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      # Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudWatchLogsAccess
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
              - Sid: S3Access
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketForLambda}
                  - !Sub arn:aws:s3:::${S3BucketForLambda}/*
              - Sid: CloudFormationAccess
                Effect: Allow
                Action: cloudformation:ValidateTemplate
                Resource: "*"
  # CI/CD CodeBuild Create
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: ModuleName
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/ubuntu-base:14.04
        EnvironmentVariables:
          - Name: S3_BUCKET
            Value: !Ref S3BucketForLambda
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yaml

Outputs:
  BucketName:
    Value: !Ref S3BucketForLambda
    Export: 
      Name: !Sub ${AWS::StackName}-BucketName
