AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # S3 Bucket Create
  S3BucketForLambda:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-mtc-lambda
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  # S3 Bucket Policy Create
  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3BucketForLambda
      PolicyDocument:
        Statement:
          - Sid: APIReadForGetBucketObjects
            Effect: Allow
            Action: 's3:GetObject'
            Principal:
              AWS: '*'
            Resource: !Sub arn:aws:s3:::${S3BucketForLambda}/*

Outputs:
  BucketName:
    Value: !Ref S3BucketForLambda
    Export: 
      Name: !Sub ${AWS::StackName}-BucketName
