AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  MailAddress:
    Type: String

Resources:
  # CI/CD SNS Topic Create for CodePipeline
  SNSTopicNotificationCICD:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: sns-topic-notify-sms-for-pipeline
      Subscription:
        - Endpoint: !Ref MailAddress
          Protocol: email
  # CI/CD SNS Topic Policy Create for CodePipeline
  SNSTopicPolicyNotificationCICD:
    Type: AWS::SNS::TopicPolicy
    Properties: 
      PolicyDocument: 
        Version: '2008-10-17'
        Statement:
        - Sid: AWSCodeStarNotifications_publish
          Effect: Allow
          Principal: 
            Service: codestar-notifications.amazonaws.com
          Action:
            - SNS:Publish
          Resource: !Ref SNSTopicNotificationCICD
      Topics: 
        - !Ref SNSTopicNotificationCICD

Outputs:
  SNSTopicName:
    Value: !Ref SNSTopicNotificationCICD
    Export: 
      Name: !Sub ${AWS::StackName}-SNSTopicName
