swagger: "2.0"
info:
  description: "筋トレカウンターアプリ用のAPI"
  version: "1.0.0"
  title: "api"
basePath: "/api"
tags:
  - name: "Version"
schemes:
  - "https"
paths:
  /api/result:
    post:
      tags:
        - "Version"
      summary: "筋トレ実施結果の保存"
      description: "筋トレ実施結果を保存します。"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Version"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:530421169424:function:MtcCfnApi-function/invocations
        responses:
          default:
            statusCode: 200
        passthroughBehavior: when_no_match
        type: aws_proxy
definitions:
  Version:
    type: "object"
    required:
      - "python"
    properties:
      python:
        type: "string"